import {
  User,
  Lead,
  Deal,
  Company,
  Contact,
  Task,
  Activity,
  Payment,
  Product,
  Project,
  Organization,
  PipelineStageConfig,
  LossReason,
  CustomField,
} from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Malik",
    email: "sarah@bashar.ai",
    role: "Admin",
    active: true,
    initials: "SM",
    phone: "+1 (555) 234-5678",
    title: "Head of Sales",
    leadsCreated: 42,
    dealsWon: 18,
    tasksCompleted: 156,
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@bashar.ai",
    role: "Sales User",
    active: true,
    initials: "JD",
    phone: "+1 (555) 345-6789",
    title: "Senior Account Executive",
    leadsCreated: 29,
    dealsWon: 12,
    tasksCompleted: 98,
    createdAt: "2024-02-01T09:00:00Z",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@bashar.ai",
    role: "Manager",
    active: true,
    initials: "MJ",
    phone: "+1 (555) 456-7890",
    title: "Sales Director",
    leadsCreated: 15,
    dealsWon: 24,
    tasksCompleted: 82,
    createdAt: "2024-01-10T10:00:00Z",
  },
];

export const mockProjects: Project[] = [
  { id: "proj-1", name: "Enterprise Expansion", code: "EXP-2025", active: true },
  { id: "proj-2", name: "Mid-Market Growth", code: "MMG-2025", active: true },
  { id: "proj-3", name: "SaaS Partnerships", code: "PART-2025", active: true },
];

export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    name: "Acme Technologies",
    industry: "SaaS / Cloud",
    website: "https://acme.io",
    phone: "+1 (555) 100-2000",
    email: "contact@acme.io",
    address: "100 Market St, San Francisco, CA",
    city: "San Francisco",
    country: "USA",
    size: "50-200",
    tier: "Tier 1",
    annualRevenue: 25000000,
    ownerEmail: "sarah@bashar.ai",
    createdAt: "2024-02-10T09:30:00Z",
    description: "Enterprise workflow automation platform.",
  },
  {
    id: "comp-2",
    name: "Apex Logistics",
    industry: "Supply Chain",
    website: "https://apexlogistics.com",
    phone: "+1 (555) 200-3000",
    email: "hello@apexlogistics.com",
    address: "450 Industrial Pkwy, Chicago, IL",
    city: "Chicago",
    country: "USA",
    size: "200-500",
    tier: "Tier 1",
    annualRevenue: 45000000,
    ownerEmail: "john@bashar.ai",
    createdAt: "2024-03-01T11:00:00Z",
    description: "Global 3PL and shipping logistics aggregator.",
  },
  {
    id: "comp-3",
    name: "Nexus Health",
    industry: "HealthTech",
    website: "https://nexushealth.co",
    phone: "+1 (555) 300-4000",
    email: "info@nexushealth.co",
    address: "700 Medical Center Blvd, Austin, TX",
    city: "Austin",
    country: "USA",
    size: "20-50",
    tier: "Tier 2",
    annualRevenue: 8000000,
    ownerEmail: "sarah@bashar.ai",
    createdAt: "2024-03-15T14:20:00Z",
    description: "AI triage and patient record management.",
  },
];

export const mockContacts: Contact[] = [
  {
    id: "cnt-1",
    companyId: "comp-1",
    name: "Alice Vance",
    email: "alice@acme.io",
    phone: "+1 (555) 100-2001",
    title: "VP of Engineering",
    isPrimary: true,
  },
  {
    id: "cnt-2",
    companyId: "comp-2",
    name: "Bob Stone",
    email: "bob@apexlogistics.com",
    phone: "+1 (555) 200-3002",
    title: "Chief Operating Officer",
    isPrimary: true,
  },
  {
    id: "cnt-3",
    companyId: "comp-3",
    name: "Claire Bennett",
    email: "claire@nexushealth.co",
    phone: "+1 (555) 300-4003",
    title: "Head of Operations",
    isPrimary: true,
  },
];

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Alice Vance",
    company: "Acme Technologies",
    companyId: "comp-1",
    email: "alice@acme.io",
    phone: "+1 (555) 100-2001",
    title: "VP of Engineering",
    city: "San Francisco",
    country: "USA",
    stage: "Meeting Scheduled",
    source: "Website",
    value: 75000,
    ownerEmail: "sarah@bashar.ai",
    projectId: "proj-1",
    priority: "High",
    score: 85,
    notes: "Very enthusiastic about AI integration. Meeting planned for demo.",
    tags: ["Hot", "Enterprise"],
    createdAt: "2024-03-01T10:00:00Z",
    lastActivityAt: "2024-03-05T14:30:00Z",
  },
  {
    id: "lead-2",
    name: "Bob Stone",
    company: "Apex Logistics",
    companyId: "comp-2",
    email: "bob@apexlogistics.com",
    phone: "+1 (555) 200-3002",
    title: "Chief Operating Officer",
    city: "Chicago",
    country: "USA",
    stage: "Proposal Sent",
    source: "Referral",
    value: 120000,
    ownerEmail: "john@bashar.ai",
    projectId: "proj-1",
    priority: "High",
    score: 92,
    notes: "Reviewing multi-seat enterprise proposal.",
    tags: ["High Value", "Logistics"],
    createdAt: "2024-03-02T11:15:00Z",
    lastActivityAt: "2024-03-04T16:00:00Z",
  },
  {
    id: "lead-3",
    name: "Claire Bennett",
    company: "Nexus Health",
    companyId: "comp-3",
    email: "claire@nexushealth.co",
    phone: "+1 (555) 300-4003",
    title: "Head of Operations",
    city: "Austin",
    country: "USA",
    stage: "Connected",
    source: "LinkedIn",
    value: 45000,
    ownerEmail: "sarah@bashar.ai",
    projectId: "proj-2",
    priority: "Medium",
    score: 68,
    notes: "Initial phone call completed. Expressed interest in analytics.",
    tags: ["HealthTech"],
    createdAt: "2024-03-03T15:00:00Z",
    lastActivityAt: "2024-03-06T09:00:00Z",
  },
  {
    id: "lead-4",
    name: "David Kim",
    company: "Starlight Retail",
    email: "david@starlight.com",
    phone: "+1 (555) 400-5001",
    title: "General Manager",
    city: "New York",
    country: "USA",
    stage: "New",
    source: "Cold Call",
    value: 30000,
    ownerEmail: "john@bashar.ai",
    projectId: "proj-2",
    priority: "Low",
    score: 45,
    notes: "New inbound enquiry via cold outreach.",
    tags: ["Retail"],
    createdAt: "2024-03-07T08:30:00Z",
  },
  {
    id: "lead-5",
    name: "Elena Rostova",
    company: "Quantum Financial",
    email: "elena@quantumfin.com",
    phone: "+1 (555) 500-6001",
    title: "Chief Risk Officer",
    city: "Boston",
    country: "USA",
    stage: "Negotiation",
    source: "Conference",
    value: 150000,
    ownerEmail: "sarah@bashar.ai",
    projectId: "proj-1",
    priority: "High",
    score: 95,
    notes: "Final legal and security review in progress.",
    tags: ["Fintech", "High Value"],
    createdAt: "2024-02-20T12:00:00Z",
    lastActivityAt: "2024-03-08T17:00:00Z",
  },
  {
    id: "lead-6",
    name: "Frank Miller",
    company: "Solaris Clean Energy",
    email: "frank@solaris.org",
    phone: "+1 (555) 600-7001",
    title: "VP of Sustainability",
    city: "Denver",
    country: "USA",
    stage: "Won",
    source: "Partner",
    value: 85000,
    ownerEmail: "sarah@bashar.ai",
    projectId: "proj-3",
    priority: "Medium",
    score: 100,
    notes: "Contract signed! Onboarding kickoff next week.",
    tags: ["Energy", "Won"],
    createdAt: "2024-01-25T14:00:00Z",
    lastActivityAt: "2024-03-02T10:00:00Z",
  },
];

export const mockDeals: Deal[] = [
  {
    id: "deal-1",
    title: "Acme Enterprise License",
    value: 75000,
    stage: "Meeting Scheduled",
    leadId: "lead-1",
    ownerEmail: "sarah@bashar.ai",
    company: "Acme Technologies",
    contactName: "Alice Vance",
    expectedCloseDate: "2025-04-15",
    probability: 60,
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "deal-2",
    title: "Apex Fleet Dispatch System",
    value: 120000,
    stage: "Proposal Sent",
    leadId: "lead-2",
    ownerEmail: "john@bashar.ai",
    company: "Apex Logistics",
    contactName: "Bob Stone",
    expectedCloseDate: "2025-03-30",
    probability: 75,
    createdAt: "2024-03-02T11:15:00Z",
  },
  {
    id: "deal-3",
    title: "Quantum Risk Suite",
    value: 150000,
    stage: "Negotiation",
    leadId: "lead-5",
    ownerEmail: "sarah@bashar.ai",
    company: "Quantum Financial",
    contactName: "Elena Rostova",
    expectedCloseDate: "2025-03-25",
    probability: 90,
    createdAt: "2024-02-20T12:00:00Z",
  },
  {
    id: "deal-4",
    title: "Solaris Clean Energy Platform",
    value: 85000,
    stage: "Won",
    leadId: "lead-6",
    ownerEmail: "sarah@bashar.ai",
    company: "Solaris Clean Energy",
    contactName: "Frank Miller",
    won: true,
    closeDate: "2024-03-02",
    probability: 100,
    createdAt: "2024-01-25T14:00:00Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Enterprise Core Platform",
    price: 45000,
    category: "Software",
    sku: "ECP-01",
    active: true,
    description: "Annual subscription for up to 50 users.",
  },
  {
    id: "prod-2",
    name: "AI Analytics Add-on",
    price: 15000,
    category: "Add-on",
    sku: "AIA-02",
    active: true,
    description: "Predictive pipeline insights and revenue modeling.",
  },
  {
    id: "prod-3",
    name: "Custom Integration & SLA",
    price: 25000,
    category: "Services",
    sku: "CIS-03",
    active: true,
    description: "Dedicated account manager and bespoke API pipelines.",
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay-1",
    dealId: "deal-4",
    amount: 42500,
    date: "2024-03-02T11:00:00Z",
    status: "Completed",
    method: "Bank Wire",
    reference: "WIRE-89327",
  },
  {
    id: "pay-2",
    dealId: "deal-4",
    amount: 42500,
    date: "2024-04-02T11:00:00Z",
    status: "Pending",
    method: "Bank Wire",
    reference: "WIRE-89328",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Send updated security compliance brief",
    description: "Prepare SOC2 Type II report and attach to proposal email.",
    status: "Pending",
    priority: "High",
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    assigneeEmail: "sarah@bashar.ai",
    leadId: "lead-5",
    dealId: "deal-3",
    createdAt: "2024-03-05T09:00:00Z",
  },
  {
    id: "task-2",
    title: "Follow up with Bob Stone on pricing questions",
    description: "Clarify per-seat dispatch licenses and payment terms.",
    status: "In Progress",
    priority: "High",
    dueDate: new Date().toISOString(),
    assigneeEmail: "john@bashar.ai",
    leadId: "lead-2",
    dealId: "deal-2",
    createdAt: "2024-03-04T10:30:00Z",
  },
  {
    id: "task-3",
    title: "Schedule product demo with Alice",
    description: "Set up Zoom meeting link and send calendar invites.",
    status: "Completed",
    priority: "Medium",
    dueDate: "2024-03-03T16:00:00Z",
    assigneeEmail: "sarah@bashar.ai",
    leadId: "lead-1",
    createdAt: "2024-03-02T14:00:00Z",
    completedAt: "2024-03-03T15:30:00Z",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    leadId: "lead-1",
    dealId: "deal-1",
    userEmail: "sarah@bashar.ai",
    channel: "Call",
    outcome: "Connected",
    notes: "30-minute intro call. Alice wants to demo the system to her CTO next Tuesday.",
    createdAt: "2024-03-05T14:30:00Z",
  },
  {
    id: "act-2",
    leadId: "lead-2",
    dealId: "deal-2",
    userEmail: "john@bashar.ai",
    channel: "Email",
    outcome: "Sent",
    notes: "Sent proposal draft #2 with tiered fleet pricing breakdown.",
    createdAt: "2024-03-04T16:00:00Z",
  },
  {
    id: "act-3",
    leadId: "lead-3",
    userEmail: "sarah@bashar.ai",
    channel: "WhatsApp",
    outcome: "Read",
    notes: "Shared quick 2-minute product walkthrough video.",
    createdAt: "2024-03-06T09:00:00Z",
  },
];

export const mockOrganization: Organization = {
  id: "org-1",
  name: "Bashaar Enterprises Inc.",
  currency: "USD",
  timezone: "America/New_York",
  fiscalYearStart: "January",
  address: "123 Innovation Way, Tech District, NY",
  phone: "+1 (800) 555-0199",
  website: "https://bashar.ai",
};

export const mockPipelineStages: PipelineStageConfig[] = [
  { id: "stg-1", name: "New", color: "#4285f4", order: 1, winProbability: 10 },
  { id: "stg-2", name: "Attempted", color: "#9c27b0", order: 2, winProbability: 20 },
  { id: "stg-3", name: "Connected", color: "#00c853", order: 3, winProbability: 35 },
  { id: "stg-4", name: "Interested", color: "#ffc107", order: 4, winProbability: 50 },
  { id: "stg-5", name: "Meeting Scheduled", color: "#f4c542", order: 5, winProbability: 65 },
  { id: "stg-6", name: "Proposal Sent", color: "#ff6f00", order: 6, winProbability: 75 },
  { id: "stg-7", name: "Negotiation", color: "#ff4444", order: 7, winProbability: 85 },
  { id: "stg-8", name: "Won", color: "#00c853", order: 8, winProbability: 100 },
  { id: "stg-9", name: "Lost", color: "#ff4444", order: 9, winProbability: 0 },
];

export const mockLossReasons: LossReason[] = [
  { id: "lr-1", name: "Competitor Price", active: true },
  { id: "lr-2", name: "Missing Feature", active: true },
  { id: "lr-3", name: "Budget Constraints", active: true },
  { id: "lr-4", name: "No Decision / Delayed", active: true },
  { id: "lr-5", name: "Poor Fit", active: true },
];

export const mockCustomFields: CustomField[] = [
  { id: "cf-1", name: "Lead Score Tier", entityType: "lead", fieldType: "text", required: false },
  { id: "cf-2", name: "Renewal Date", entityType: "deal", fieldType: "date", required: false },
];
